const scenes=[
 {title:'WELCOME TO THE CHECKPOINT',alt:'Two young people arrive between Resume District and Interview Arena.'},
 {title:'YOUR READINESS STARTS HERE',alt:'A futuristic confidence checkpoint with clothing and preparation icons.',activity:'scan'},
 {title:'PAUSE AND PREPARE',alt:'A young person pauses at a desk before preparing for the next day.'},
 {title:'PRESENT THE BEST VERSION OF YOU',alt:'Two young people explore personal readiness choices in a smart mirror.',activity:'icons'},
 {title:'SMALL HABITS, REAL CONFIDENCE',alt:'A young person begins organizing clothing and hygiene supplies.'},
 {title:'NOTICE WHAT HELPS',alt:'A mirror scene shows the connection between preparation and confidence.'},
 {title:'BUILD YOUR TOOLKIT',alt:'A mentor and participant review practical hygiene and preparation supplies.',activity:'needs'},
 {title:'YOUR ROUTINE, YOUR WAY',alt:'A participant checks their readiness in a mirror.'},
 {title:'PACK FOR SUCCESS',alt:'A participant prepares clean clothes, shoes, and personal care items.',activity:'kit'},
 {title:'CONFIDENCE SHOWS',alt:'A prepared participant notices positive body language in the mirror.'},
 {title:'STEP FORWARD',alt:'A participant follows a glowing path toward the next opportunity.'},
 {title:'PREPARATION IN REAL LIFE',alt:'Scenes show preparation routines in different work environments.'},
 {title:'HANDLE THE MOMENT',alt:'Two young people explore common preparation situations.',activity:'situations'},
 {title:'MAKE A PLAN THAT WORKS',alt:'A circular routine map surrounds a participant and mentor.',activity:'routine'},
 {title:'INTERVIEW ARENA AWAITS',alt:'A prepared participant approaches the entrance to Interview Arena.'},
 {title:'CONFIDENCE CHECKPOINT COMPLETE',alt:'A participant and mentor review progress and prepare to continue.',activity:'reflection'}
];
const imageFiles=[2,3,4,5,6,7,8,9,10,11,12,13,15,16,17,18].map(n=>`assets/image${n}.png`);
let state=JSON.parse(localStorage.getItem('lu-confidence-state')||'null')||{scene:0,xp:0,earned:{},answers:{},viewed:{},narrated:{},complete:false,settings:{auto:true,captions:true,reduce:false}};
let profileName='Participant';
state.narrated ||= {};
setTimeout(initializeCloud,0);
const $=s=>document.querySelector(s), image=$('#sceneImage'),video=$('#narration'),next=$('#nextBtn'),narrBtn=$('#narrationBtn'),hotspots=$('#hotspots'),dialog=$('#activityDialog');
const activities={
 scan:{title:'Your readiness scan',xp:50,render:()=>`<div class="lesson"><p class="lesson-intro">Preparation is not about being perfect. Choose the habits that would help you feel ready and comfortable.</p>${choices('scanHabits',['Set out clean clothes','Bathed or showered','Brush teeth and check breath','Clean hands and nails','Pack what I need','Plan enough travel time'],true)}<label class="field"><span>One habit I want to strengthen</span><input data-answer="habitGoal" placeholder="Example: Set out my clothes the night before"></label></div>`},
 needs:{title:'What support would make preparation easier?',xp:75,render:()=>`<div class="lesson"><p class="lesson-intro">Needs are not failures. Identifying a barrier helps your Career Coach connect you with practical support.</p>${choices('needs',['Cost of hygiene products','Access to laundry','Access to a shower or reliable housing','Transportation','Work, school, or family schedule','Help building a routine','Nothing right now','Something I want to discuss privately with my Career Coach'],true)}<label class="field"><span>Optional note for my Career Coach</span><textarea data-answer="supportNote" placeholder="Share only what you are comfortable sharing."></textarea></label></div>`},
 kit:{title:'Build a ready-to-go kit',xp:50,render:()=>`<div class="lesson"><p class="lesson-intro">Choose what would be useful for your interview, first day, or work shift.</p>${choices('kit',['Clean shirt or uniform','Deodorant','Toothbrush or breath care','Hair care item','Water bottle','Documents or identification','Notebook and pen','Transportation plan'],true)}</div>`},
 situations:{title:'Handle the moment',xp:75,render:()=>`<div class="lesson"><p class="lesson-intro">Pick the response that protects your confidence and helps you move forward.</p>${scenario('s1','Your clean interview shirt is wrinkled.',['Wear it without checking','Steam or carefully press it, or choose another clean option','Cancel the interview'],1)}${scenario('s2','You realize transportation will make you late.',['Contact the employer early and explain briefly','Say nothing and arrive whenever you can','Skip the interview'],0)}${scenario('s3','A strong fragrance is bothering someone nearby.',['Add more fragrance','Ignore them','Reduce or avoid fragrance when possible'],2)}</div>`},
 routine:{title:'Build your confidence routine',xp:50,render:()=>`<div class="lesson"><p class="lesson-intro">Choose when you will complete each step. A realistic routine is easier to repeat.</p>${selectRow('Clothes ready','clothesWhen')}${selectRow('Bathing or showering','washWhen')}${selectRow('Teeth and breath care','teethWhen')}${selectRow('Bag and documents packed','bagWhen')}<label class="field"><span>My reminder</span><input data-answer="reminder" placeholder="Example: Set an alarm for 8:00 PM"></label></div>`},
 reflection:{title:'Complete your Confidence Checkpoint',xp:75,render:()=>`<div class="lesson"><p class="lesson-intro">Your earlier choices are already included. Finish with a quick confidence check and one commitment for your personal readiness plan.</p><label class="field"><span>How confident do you feel about arriving clean, prepared, and ready?</span><select data-answer="confidence"><option value="">Choose one</option><option>Extremely confident</option><option>Somewhat confident</option><option>Neutral</option><option>Somewhat not confident</option><option>Extremely not confident</option></select></label><label class="field"><span>One preparation habit I will practice</span><textarea data-answer="practice" placeholder="What will you do before your next interview or first day?"></textarea></label></div>`}
};
const iconLessons=[
 {label:'Clean clothing',text:'Clean, role-appropriate clothing signals preparation. It does not need to be new or expensive—clean, safe, comfortable, and appropriate for the setting is the goal.',pos:[27,31]},
 {label:'Personal hygiene',text:'Bathing or showering, deodorant, and breath care help you feel comfortable and reduce distractions during an interview or shift.',pos:[68,29]},
 {label:'Hair, hands & nails',text:'Clean hair, hands, and nails support workplace hygiene and help create a prepared first impression.',pos:[72,58]},
 {label:'Fragrance awareness',text:'Strong fragrance can trigger allergies or sensory discomfort. A light or fragrance-free approach is often the safest workplace choice.',pos:[28,62]}
];
function choices(key,items,multi=false){const saved=state.answers[key]||[];return `<div class="choice-list">${items.map((v,i)=>`<label class="choice ${saved.includes(v)?'selected':''}"><input type="${multi?'checkbox':'radio'}" name="${key}" value="${esc(v)}" ${saved.includes(v)?'checked':''}><span>${v}</span></label>`).join('')}</div>`}
function scenario(key,prompt,options,correct){return `<div class="field scenario"><span>${prompt}</span>${options.map((v,i)=>`<label class="choice"><input type="radio" name="${key}" value="${i}" data-correct="${correct}"><span>${v}</span></label>`).join('')}</div>`}
function selectRow(label,key){return `<label class="field"><span>${label}</span><select data-answer="${key}"><option value="">Choose a time</option><option>The night before</option><option>In the morning</option><option>Before leaving</option><option>At the workplace</option></select></label>`}
function esc(v){return String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function save(){state.updatedAt=new Date().toISOString();localStorage.setItem('lu-confidence-state',JSON.stringify(state));window.LUCloud?.queueSave(state)}
function asset(n){return imageFiles[n]}
function narration(n){return `assets/media${n+1}.mp4`}
function requiredComplete(){const a=scenes[state.scene].activity;if(!a)return true;if(a==='icons')return iconLessons.every((_,i)=>state.viewed[`4-${i}`]);return !!state.earned[a]}
function render(){
 const n=state.scene,s=scenes[n];image.src=asset(n);image.alt=s.alt;video.src=narration(n);video.hidden=!state.settings.captions;$('#chapter').textContent=s.title;$('#sceneLabel').textContent=`SCENE ${n+1} OF ${scenes.length}`;$('#progressFill').style.width=`${(n+1)/scenes.length*100}%`;$('#xp').textContent=`${state.xp} XP`;$('#prevBtn').disabled=n===0;$('#backBtn').disabled=n===0;next.textContent=n===15?(state.complete?'View readiness report →':'Complete checkpoint →'):'Continue →';narrBtn.textContent='▶ Play narration & captions';narrBtn.hidden=false;hotspots.innerHTML='';$('#exploreStatus').hidden=true;
 if(state.narrated[n]){narrBtn.textContent='↻ Replay narration';reveal()}else if(state.settings.auto){video.play().then(()=>{narrBtn.textContent='▹ Skip narration'}).catch(()=>{});}
 video.onplay=()=>narrBtn.textContent='▹ Skip narration';video.onended=()=>{state.narrated[n]=true;save();narrBtn.textContent='↻ Replay narration';reveal()};
 next.disabled=!!s.activity&&!requiredComplete();
}
function reveal(){const a=scenes[state.scene].activity;if(!a)return;if(a==='icons'){iconLessons.forEach((x,i)=>addHotspot(i,x.pos,()=>openIcon(i)));setExplore(iconLessons.filter((_,i)=>state.viewed[`4-${i}`]).length,4)}else{const positions={scan:[52,57],needs:[44,58],kit:[70,57],situations:[55,53],routine:[50,52],reflection:[50,60]};addHotspot(a,positions[a],()=>openActivity(a));setExplore(state.earned[a]?1:0,1)} }
function addHotspot(id,pos,fn){const b=document.createElement('button');b.className='hotspot';b.style.left=`calc(${pos[0]}% - 24px)`;b.style.top=`calc(${pos[1]}% - 24px)`;const done=scenes[state.scene].activity==='icons'?state.viewed[`4-${id}`]:state.earned[id];if(done)b.classList.add('done');b.textContent=done?'✓':'✦';b.setAttribute('aria-label',done?'Explored learning activity':'Explore learning activity');b.onclick=fn;hotspots.appendChild(b)}
function setExplore(done,total){const el=$('#exploreStatus');el.hidden=false;el.textContent=done===total?`✓ ${total===1?'Activity complete':'All elements explored'}`:`✦ Explore ${done} of ${total}`}
function openIcon(i){const item=iconLessons[i];$('#modalTitle').textContent=item.label;$('#modalBody').innerHTML=`<div class="lesson"><div class="flip" id="singleFlip" tabindex="0"><div class="flip-inner"><div class="flip-face"><b>${item.label}</b><span>Click to reveal the workplace connection.</span></div><div class="flip-face flip-back"><b>Why it matters</b><span>${item.text}</span></div></div></div><div class="modal-actions"><button id="iconDone">Mark explored · +15 XP</button></div></div>`;dialog.showModal();const flip=$('#singleFlip');flip.onclick=()=>flip.classList.toggle('open');flip.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();flip.classList.toggle('open')}};$('#iconDone').onclick=()=>{const k=`4-${i}`;if(!state.viewed[k]){state.viewed[k]=true;state.xp+=15;toast('+15 XP · Insight explored')}save();dialog.close();render()}}
function openActivity(key){const a=activities[key];$('#modalTitle').textContent=a.title;$('#modalBody').innerHTML=a.render()+`<div class="modal-actions"><button id="completeActivity">${state.earned[key]?'Update my response':`Save and earn ${a.xp} XP`}</button></div>`;hydrate();wireChoices();dialog.showModal();$('#completeActivity').onclick=()=>completeActivity(key,a)}
function hydrate(){document.querySelectorAll('[data-answer]').forEach(el=>{if(state.answers[el.dataset.answer]!=null)el.value=state.answers[el.dataset.answer]})}
function wireChoices(){document.querySelectorAll('.choice input').forEach(inp=>inp.onchange=()=>{if(inp.type==='checkbox'){inp.closest('.choice').classList.toggle('selected',inp.checked)}else{document.querySelectorAll(`input[name="${inp.name}"]`).forEach(x=>x.closest('.choice').classList.toggle('selected',x.checked))}})}
function collect(){document.querySelectorAll('[data-answer]').forEach(el=>state.answers[el.dataset.answer]=el.value);document.querySelectorAll('.choice-list').forEach(list=>{const first=list.querySelector('input');if(first)state.answers[first.name]=[...list.querySelectorAll('input:checked')].map(x=>x.value)})}
function completeActivity(key,a){collect();if(key==='situations'){const groups=['s1','s2','s3'];if(groups.some(k=>!document.querySelector(`input[name="${k}"]:checked`))){toast('Choose a response for each situation');return}const correct=groups.every(k=>{const x=document.querySelector(`input[name="${k}"]:checked`);return x.value===x.dataset.correct});if(!correct){toast('Almost—look for the response that prepares, communicates, or adapts.');return}state.answers.situations='All three readiness situations completed'}
 if(key==='reflection'&&(!state.answers.confidence||!state.answers.practice)){toast('Add your confidence and preparation habit to finish.');return}
 if(!state.earned[key]){state.earned[key]=true;state.xp+=a.xp;toast(`+${a.xp} XP · Learning saved`)}
 if(key==='reflection'){state.complete=true;state.completionDate=new Date().toISOString();save();dialog.close();showReport();return}save();dialog.close();render()}
function nextScene(){if(state.scene===15){if(state.complete)showReport();else openActivity('reflection');return}if(!requiredComplete()){toast('Complete the highlighted activity before continuing.');return}state.scene++;save();render()}
function prevScene(){if(state.scene>0){state.scene--;save();render()}}
function toggleNarration(){if(!video.paused){video.pause();video.currentTime=video.duration||0;state.narrated[state.scene]=true;save();narrBtn.textContent='↻ Replay narration';reveal()}else{video.currentTime=0;video.play().catch(()=>{});narrBtn.textContent='▹ Skip narration'}}
function showReport(){
 video.pause();$('#app').hidden=true;const r=$('#report');r.hidden=false;
 const habits=(state.answers.scanHabits||[]).join(', ')||'Not recorded';
 const needs=(state.answers.needs||[]).join(', ')||'Nothing recorded';
 const kit=(state.answers.kit||[]).join(', ')||'Not recorded';
 r.innerHTML=`<small>LEVEL UP · CONFIDENCE CHECKPOINT</small><h1>${esc(profileName)}’s Interview Readiness Plan</h1><p>Completed with <b>${state.xp} XP</b>. This summary reflects learning demonstrated throughout the checkpoint.</p><div class="report-grid"><div class="report-card"><h2>Readiness habits</h2><p>${esc(habits)}</p><p><b>Habit to strengthen:</b> ${esc(state.answers.habitGoal||'Not recorded')}</p></div><div class="report-card"><h2>Confidence</h2><p>${esc(state.answers.confidence||'Not recorded')}</p><p><b>Next habit:</b> ${esc(state.answers.practice||'Not recorded')}</p></div><div class="report-card"><h2>Support and needs assessment</h2><p>${esc(needs)}</p><p>${esc(state.answers.supportNote||'No additional note')}</p></div><div class="report-card"><h2>Ready-to-go kit</h2><p>${esc(kit)}</p></div><div class="report-card"><h2>My routine</h2><p>Clothes: ${esc(state.answers.clothesWhen||'Not set')}<br>Bathing/showering: ${esc(state.answers.washWhen||'Not set')}<br>Teeth/breath: ${esc(state.answers.teethWhen||'Not set')}<br>Bag/documents: ${esc(state.answers.bagWhen||'Not set')}</p><p><b>Reminder:</b> ${esc(state.answers.reminder||'Not set')}</p></div></div><div class="report-actions"><button id="printReport">Save or print PDF</button><button id="downloadReport">Download PDF</button><button id="returnLesson" class="return">Return to checkpoint</button><button id="arenaBtn">Continue to Interview Arena →</button></div>`;
 $('#printReport').onclick=()=>window.print();$('#downloadReport').onclick=downloadPdf;
 $('#returnLesson').onclick=()=>{r.hidden=true;$('#app').hidden=false;render()};
 $('#arenaBtn').onclick=async()=>{await window.LUCloud?.flush(state);location.href=window.LEVEL_UP_CONFIG.PORTAL_URL+'?completed=confidence-checkpoint&next=interview-arena'};
}
function downloadPdf(){const lines=[`LEVEL UP - CONFIDENCE CHECKPOINT`,`MY INTERVIEW READINESS PLAN`,`XP earned: ${state.xp}`,`Confidence: ${state.answers.confidence||'Not recorded'}`,`Habit I will practice: ${state.answers.practice||'Not recorded'}`,`Readiness habits: ${(state.answers.scanHabits||[]).join(', ')||'Not recorded'}`,`Support needs: ${(state.answers.needs||[]).join(', ')||'Not recorded'}`,`Support note: ${state.answers.supportNote||'None'}`,`Ready-to-go kit: ${(state.answers.kit||[]).join(', ')||'Not recorded'}`];const wrapped=[];lines.forEach(l=>{while(l.length>82){wrapped.push(l.slice(0,82));l=l.slice(82)}wrapped.push(l)});const body=wrapped.map((l,i)=>`BT /F1 ${i===0?18:11} Tf 55 ${750-i*28} Td (${pdfEsc(l)}) Tj ET`).join('\n');const objs=[`<< /Type /Catalog /Pages 2 0 R >>`,`<< /Type /Pages /Kids [3 0 R] /Count 1 >>`,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>`,`<< /Length ${body.length} >>\nstream\n${body}\nendstream`,`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`];let pdf='%PDF-1.4\n',offs=[0];objs.forEach((o,i)=>{offs.push(pdf.length);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`+offs.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size ${objs.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;const blob=new Blob([pdf],{type:'application/pdf'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Confidence-Checkpoint-Readiness-Plan.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function pdfEsc(s){return String(s).replace(/[^\x20-\x7E]/g,'').replace(/([\\()])/g,'\\$1')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2600)}
async function initializeCloud(){
 const gate=$('#entryGate'),title=$('#gateTitle'),message=$('#gateMessage'),list=$('#gateProgress'),action=$('#gateAction'),cloud=$('#cloudStatus');
 gate.hidden=false;video.pause();
 const result=await window.LUCloud.init();
 if(!result.authenticated){title.textContent='Sign in to continue your journey';message.textContent='Confidence Checkpoint uses your Level Up profile to save progress across browsers.';list.innerHTML='<span>☁ Cloud progress</span><span>✓ One participant profile</span>';action.textContent='Sign in through My Journey';action.href=window.LEVEL_UP_CONFIG.PORTAL_URL;cloud.textContent='☁ Sign in required';return}
 profileName=result.profile?.display_name||result.user?.email?.split('@')[0]||'Participant';
 const discoveryDone=result.prerequisites?.discovery,resumeDone=result.prerequisites?.resume;
 if(!discoveryDone||!resumeDone){title.textContent='Finish the earlier checkpoints first';message.textContent='Confidence Checkpoint opens after Discovery and Resume District are complete.';list.innerHTML=`<span>${discoveryDone?'✓':'○'} Discovery</span><span>${resumeDone?'✓':'○'} Resume District</span><span>○ Confidence Checkpoint</span>`;action.textContent='Return to My Journey';action.href=window.LEVEL_UP_CONFIG.PORTAL_URL;cloud.textContent='☁ Journey checked';return}
 const cloudState=result.progress?.journey_state;
 if(cloudState&&(!state.updatedAt||new Date(result.progress.updated_at)>new Date(state.updatedAt))){state={...state,...cloudState,settings:{...state.settings,...(cloudState.settings||{})},narrated:cloudState.narrated||{}};localStorage.setItem('lu-confidence-state',JSON.stringify(state))}
 gate.hidden=true;cloud.textContent='☁ Cloud synced';render();
}
window.addEventListener('lu-cloud-status',event=>{const cloud=$('#cloudStatus');if(event.detail==='saving')cloud.textContent='☁ Saving…';if(event.detail==='synced')cloud.textContent='☁ Cloud synced';if(event.detail==='error')cloud.textContent='⚠ Saved on this device'});
$('#nextBtn').onclick=nextScene;$('#prevBtn').onclick=prevScene;$('#backBtn').onclick=prevScene;narrBtn.onclick=toggleNarration;$('#closeModal').onclick=()=>dialog.close();$('#accessBtn').onclick=()=>$('#accessDialog').showModal();$('.close-access').onclick=()=>$('#accessDialog').close();$('#autoPlay').checked=state.settings.auto;$('#showCaptions').checked=state.settings.captions;$('#reduceMotion').checked=state.settings.reduce;$('#autoPlay').onchange=e=>{state.settings.auto=e.target.checked;save()};$('#showCaptions').onchange=e=>{state.settings.captions=e.target.checked;video.hidden=!e.target.checked;save()};$('#reduceMotion').onchange=e=>{state.settings.reduce=e.target.checked;document.body.classList.toggle('reduce-motion',e.target.checked);save()};$('#soundBtn').onclick=()=>{video.muted=!video.muted;$('#soundBtn').textContent=video.muted?'🔇':'🔊'};$('#resetBtn').onclick=()=>{if(confirm('Reset this checkpoint and clear its saved progress?')){localStorage.removeItem('lu-confidence-state');location.reload()}};document.addEventListener('keydown',e=>{if(dialog.open||$('#accessDialog').open)return;if(e.key==='ArrowRight')nextScene();if(e.key==='ArrowLeft')prevScene()});render();
